name: Deploy
# trigger deploy workflow on pushing a change to main or prod branches
on:
  push:
    branches:
      - main
      - prod

jobs:
  # run liting to make sure there are no errors before deploying
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    name: Test and Lint
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    # here "needs" make sure test-lint job is successful before running deploy job
    needs: [test-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # different workspaces for main(we deploy to stage) and prod(we deploy to prod) branches
      - name: Set vars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            echo "prod" > .workspace
          else
          echo "staging" > .workspace
          fi
      - name: Push to ECR
      # vars
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # in ubuntu aws cmd is installed
      # login to aws ecr, build and push both app and proxy images
      # so the pipe allows us to pass the output of one command to another command
      # we are logging into aws version of docker hub
      # first we build the app image, tag as registry name, SHA hash generated for each commit
      # then push the image to ecr repos 
      # . runs the dockerfile in root directory 
      # proxy/ runs the dockerfile in proxy directory, so we build then push 
      # we are doing the same for the app and proxy images
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
          docker build --compress -t ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA .
          docker push ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA
          docker build --compress -t ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA proxy/
          docker push ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA
      # this job needs some sensitive info, so we add them as secrets in github projects
      # in tf we can set env variables using TF_VAR_ prefix
      # so we set the db password and django secret key as secrets in github projects
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_django_secret_key: ${{ secrets.TF_VAR_DJANGO_SECRET_KEY }}
      # we are are exporting the ecr repo image url with sha tag to tf var which was 
      # we are building in ECR above, ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA and ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA 
      # workspace is the variable, is a variable we output which we are setting in "Set vars" job
      # then "init" we are running docker compose, which will pull things from S3 bucket, so we need to init first to current instance
      # it will also pull all providers. it always run from fresh/scratch.
      # then $workspace will allow change or swtich workspace 
      # apply with -auto-approve will apply the changes without asking for confirmation, so it will give yes automatically
        run: |
          export TF_VAR_ecr_app_image="${{ vars.ECR_REPO_APP }}:$GITHUB_SHA"
          export TF_VAR_ecr_proxy_image="${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA"
          workspace=$(cat .workspace)
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy/ apply -auto-approve
